// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH4TH8W5KEml_BuzohdmXSwusjjk2h-gM',
    appId: '1:390435327714:web:16bd4cfb135fa64d4f18bb',
    messagingSenderId: '390435327714',
    projectId: 'filmgrid-1fc3e',
    authDomain: 'filmgrid-1fc3e.firebaseapp.com',
    storageBucket: 'filmgrid-1fc3e.firebasestorage.app',
    measurementId: 'G-EHES585K1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfkN-gPCQL2TzPig7EUK4-zViue_IHz60',
    appId: '1:390435327714:android:1781ffd9f742622e4f18bb',
    messagingSenderId: '390435327714',
    projectId: 'filmgrid-1fc3e',
    storageBucket: 'filmgrid-1fc3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAztJUy3Waawqs7keAvFkHvr_AK6TTgbbw',
    appId: '1:390435327714:ios:f4ea26a953ca85f24f18bb',
    messagingSenderId: '390435327714',
    projectId: 'filmgrid-1fc3e',
    storageBucket: 'filmgrid-1fc3e.firebasestorage.app',
    iosBundleId: 'com.example.filmgrid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAztJUy3Waawqs7keAvFkHvr_AK6TTgbbw',
    appId: '1:390435327714:ios:f4ea26a953ca85f24f18bb',
    messagingSenderId: '390435327714',
    projectId: 'filmgrid-1fc3e',
    storageBucket: 'filmgrid-1fc3e.firebasestorage.app',
    iosBundleId: 'com.example.filmgrid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH4TH8W5KEml_BuzohdmXSwusjjk2h-gM',
    appId: '1:390435327714:web:0fdcaf3b14ae3cb64f18bb',
    messagingSenderId: '390435327714',
    projectId: 'filmgrid-1fc3e',
    authDomain: 'filmgrid-1fc3e.firebaseapp.com',
    storageBucket: 'filmgrid-1fc3e.firebasestorage.app',
    measurementId: 'G-94M6LQBE3T',
  );

}